### ISSUE TITLE
WI.13: Refactor File System and Code Base

### ISSUE THREAD

**Issue by timmooore** [SacciadisG/Group1-SOEN341_Project_F24#104]
**Story Points:** 5
**Priority:** High
**Risk:** Medium

## Description
The repo file system and the code base need to be refactored so that the file system follows a standard structure and the code base is modular to comply with SQA best practices.

## Acceptance Criteria
- [x] File system follows a standard directory structure for a Node.js application.
- [x] Server-side code is organized in subdirectories routes, models, middlewares, based on functionality.
- [x] Client-side code is placed in views subdirectory
- [x] Assets are stored in a public subdirectory.
- [x] Vendor libraries are separate from application code.
- [x] doc directory contains documentation related to application and development such as work logs.
- [x] Tests are in a separate __test__ directory.
- [x] Version control configuration files are in repository root.

## Tasks
- #105 
- #106

**Comment by timmooore** [comment]
All criteria met.
