### ISSUE TITLE
US.01: Implement login page

### ISSUE THREAD

**Issue by NicG27** [SacciadisG/Group1-SOEN341_Project_F24#11]
**Story Points:** 3
**Priority:** High
**Risk:** Low

## Description
As a user (student or instructor), I want to log into the peer assessment system using my credentials, so that I can access the my respective dashboard and features.

## Acceptance criteria
- [ ] Users can input their username and password on a unified login page.
- [ ] Based on the user type (student or instructor), users are redirected to the appropriate dashboard upon successful login.
- [ ] If login fails, an error message is displayed, and the user is redirected back to the login page.

## Tasks
- #5 
- #6 
- #12
