### ISSUE TITLE
US.03: Create and manage instructor dashboard

### ISSUE THREAD

**Issue by NicG27** [SacciadisG/Group1-SOEN341_Project_F24#19]
**Story Points:** 8
**Priority:** High
**Risk:** High

## Description
As an instructor, I want to create and manage teams from my dashboard, so that I can organize students for peer assessments.

## Acceptance criteria
- [x] Instructors can create teams.
- [x] Instructors can upload a csv file to import a roster of students and assign them to teams.
- [x] The dashboard displays all teams created by the instructor.
- [x] Instructors can log out from the dashboard.

## Tasks
- #20 
- #21
- #22 
- #18 
- #25 
- #23 
- #24
