### ISSUE TITLE
US.04: Create and manage student dashboard

### ISSUE THREAD

**Issue by NicG27** [SacciadisG/Group1-SOEN341_Project_F24#26]
**Story Points:** 3
**Priority:** Medium
**Risk:** Low

## Description
As a student, I want to view the teams I’ve been assigned to on my dashboard, so that I know which group I belong to for peer assessments.

## Acceptance criteria
- [x] Students can view all of the teams they are assigned to.
- [x] The dashboard displays each team’s name and a list of all members.
- [x] Students can log out from the dashboard.

## Tasks
- #27 
- #28 
- #29
