### ISSUE TITLE
US.05: Basic peer assessment interface

### ISSUE THREAD

**Issue by NicG27** [SacciadisG/Group1-SOEN341_Project_F24#33]
**Story Points:** 8
**Priority:** High
**Risk:** Medium

## Description
As a student, I want an interface where I can select teammates for evaluation, so that I can begin the peer assessment process.

## Acceptance Criteria
- [x] A peer assessment page displays a list of all teammates the student can evaluate.
- [x] Students can select teammates for evaluation from the provided list.
- [x] Students can navigate from the peer assessment interface back to the student dashboard.

## Tasks
- #36 
- #37 
- #38 
- #39
