### ISSUE TITLE
US.06: Basic evaluation and submission

### ISSUE THREAD

**Issue by NicG27** [SacciadisG/Group1-SOEN341_Project_F24#34]
**Story Points:** 13
**Priority:** High
**Risk:** High

## Description
As a student, I want to be able to submit peer ratings for my teammates using a 5-point scale for the ‘cooperation’ dimension, and confirm my submission on a separate confirmation page, so that I can complete the peer assessment process.

## Acceptance Criteria
- [x] Students can rate each teammate on a 5-point scale for the cooperation dimension.
- [x] After rating teammates, students are redirected to a confirmation page where their assessment ratings are displayed and can be modified.
- [x] Students must confirm their submission before finalizing it.
- [x] The student can no longer modify the assessment after submission.

## Tasks
- #40
- #41 
- #42 
- #43 
- #44 
- #45
