### ISSUE TITLE
US.07: Dimension-based assessment with optional comments 

### ISSUE THREAD

**Issue by NicG27** [SacciadisG/Group1-SOEN341_Project_F24#35]
**Story Points:** 13
**Priority:** Medium
**Risk:** Medium

## Description
As a student, I want to rate my teammates across multiple dimensions and provide optional feedback, so that I can give more detailed peer assessments.

## Acceptance Criteria
- [x] Students can rate teammates on the following dimensions: cooperation, conceptual contribution, practical contribution, and work ethic.
- [x] Students can provide optional comments for each dimension to give additional feedback.
- [x] After completing all assessments, students are redirected to the confirmation page where they can see and modify all of their ratings and comments.

## Tasks
- #46 
- #47 
- #48 
- #49 
- #50 
- #51
