### ISSUE TITLE
[OLD] US.01 Student Login

### ISSUE THREAD

**Issue by timmooore** [SacciadisG/Group1-SOEN341_Project_F24#4]
**As a student, I want to log in to the peer assessment system and be authenticated, so that I can securely and confidentially access and complete peer assessments of the members of my team projects.**

## Details

- New student users must register with their student IDs to obtain a username (or student IDs are used as usernames).
- New student users must enter and re-enter their passwords.
- Student user log in must be authenticated for security. Need to decide on how to authenticate.
- If possible, do validation on the strength of the chosen password.

## Tasks
- #5 
- #6 

## Acceptance criteria

- [ ] New students must register and create a password to access the system.
- [ ] Student user can log on successfully by entering their username and password.
- [ ] User information is authenticated.
- [ ] Access is denied if an incorrect username/password combination is entered.

**Comment by NicG27** [comment]
Story board has been updated. Closing old issues
