### ISSUE TITLE
US.08: Create dashboard for Instructors to view student assessments

### ISSUE THREAD

**Issue by NicG27** [SacciadisG/Group1-SOEN341_Project_F24#63]
**Story Points:** 8
**Priority:** High
**Risk:** Medium

## Description
**As an instructor, I want a dashboard where I can view all student assessments in both summarized and detailed formats. This dashboard should also allow me to search for a specific student to quickly access their individual results.**

## Acceptance Criteria
- [x] An index page is available to decide which assessment view to access.
- [x] A summarized view page displays concise assessment details.
- [x] A detailed view page displays all assessment details.
- [x] A search bar allows instructors to search for a particular student and view their results.

## Tasks
- #65
- #66
- #67
- #68
- #69
- #70
- #71
- #72
- #73
