### ISSUE TITLE
US.09: Create a view page for students to view their evaluations

### ISSUE THREAD

**Issue by NicG27** [SacciadisG/Group1-SOEN341_Project_F24#64]
**Story Points:** 5
**Priority:** High
**Risk:** Medium

## Description
**As a student, I want a dedicated view page to review my grades and evaluations, which includes both summarized and detailed information in a single view. This page should be accessible to both the student and the instructor.**

## Acceptance Criteria
- [x] The student view page displays both summarized and detailed evaluations.
- [x] Only the evaluations of the currently logged-in student or selected student (if accessed by an instructor) are shown.
- [x] The instructor’s dashboard search bar redirects correctly to the chosen student’s evaluation page.

## Tasks
- #74 
- #75 
- #76 
- #77
