### ISSUE TITLE
US.11: Support for Instructors to Manage Multiple Courses

### ISSUE THREAD

**Issue by NicG27** [SacciadisG/Group1-SOEN341_Project_F24#88]
**Story Points:** 8
**Priority:** Medium
**Risk:** Medium

## Description
As an instructor, I want to oversee students and assessments for multiple courses, so I can manage my responsibilities across all classes effectively.

## Acceptance Criteria
- [x] Instructors can view and select individual courses from a dedicated course management page.
- [x] Students are grouped and displayed by the courses they are enrolled in.
- [x] All team and assessment routes are updated to only show data relevant to the selected course.

## Tasks
- #89 
- #90 
- #91 
- #92
- #93
